{{- if .Values.CreateStorageClass }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.DiskClassName }}
  annotations:
    helm.sh/resource-policy: keep
  {{- if eq .Values.K8SProvider "EKS" }}    
provisioner: {{ .Values.EKS_DSdriver }}
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: ext4
  {{- else if eq .Values.K8SProvider "AKS" }}  
provisioner: {{ .Values.AKS_DSdriver }}
allowVolumeExpansion: true
parameters:
  skuName: Premium_LRS
  kind: Managed
  {{- else if eq .Values.K8SProvider "GKE" }}  
provisioner: {{ .Values.GKE_DSdriver }}
allowVolumeExpansion: true
parameters:
  type: pd-standard   # pd-ssd (premium) or pd-standard  
  {{- end }}
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
  {{- if .Values.AnalysisNodeFS.enable }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.FileClassName }}
  annotations:
    helm.sh/resource-policy: keep
    {{- if eq .Values.K8SProvider "EKS" }}
provisioner: {{ .Values.EKS_FSdriver }}
allowVolumeExpansion: true
parameters:
  provisioningMode: efs-ap 
  directoryPerms: "0777"
    {{- else if eq .Values.K8SProvider "AKS" }}
provisioner: {{ .Values.AKS_FSdriver }}
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=10001
 - gid=10001
 - mfsymlinks
 - cache=strict
 - actimeo=30
 - nobrl
parameters:
  skuName: Premium_LRS
    {{- else if eq .Values.K8SProvider "GKE" }}
allowVolumeExpansion: true    
provisioner: {{ .Values.GKE_FSdriver }}
parameters:
  tier: standard  # premium or standard
    {{- end }} 
volumeBindingMode: Immediate
reclaimPolicy: Delete
  {{- end }}
{{- end }}  
---
{{- if .Values.AnalysisNodeFS.enable }}
  {{- if eq .Values.K8SProvider "EKS" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-datadir
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep  
  labels:
    console.service: console-analysis-node
spec:
  capacity:
    storage: {{ .Values.size_shared_datadir }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.FileClassName }}
  csi:
    driver: {{ .Values.EKS_FSdriver }}
    volumeHandle: {{ .Values.AnalysisNodeFS.EFSsystemID }}::{{ .Values.AnalysisNodeFS.EFSaccessPointID }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: pvc-shared-datadir
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-datadir
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep  
  labels:
    console.service: console-analysis-node
spec:
  accessModes:
{{- if .Values.AnalysisNodeFS.enable }}
    - ReadWriteMany
  storageClassName: {{ .Values.FileClassName }}
{{- else }}
    - ReadWriteOnce
  storageClassName: {{ .Values.DiskClassName }}
{{- end }}  
  resources:
    requests:
      storage: {{ .Values.size_shared_datadir }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.size_db_data }}
  storageClassName: {{ .Values.DiskClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-server-log
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep  
  labels:
    console.service: viewer-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.DiskClassName }}
  resources:
    requests:
      storage: {{ .Values.size_imagingviewer_v3_server_log }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-etl-logs
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    console.service: viewer-etl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.DiskClassName }}
  resources:
    requests:
      storage: {{ .Values.size_imagingviewer_v3_etl_logs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-aimanager-logs
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    console.service: viewer-aimanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.DiskClassName }}
  resources:
    requests:
      storage: {{ .Values.size_imagingviewer_v3_aimanager_logs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-api-logs
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    console.service: viewer-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.DiskClassName }}
  resources:
    requests:
      storage: {{ .Values.size_imagingviewer_v3_api_logs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-extendproxy-data
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep 
  labels:
    console.service: extendproxy 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.size_extendproxy_data }}
  storageClassName: {{ .Values.DiskClassName }}
