apiVersion: v1
data:
  app.config: |-
    GPT_KEY=""
{{- if .Values.CustomPostgres.enable }}
    DB_HOST="{{ .Values.CustomPostgres.host }}"
    DB_PORT={{ .Values.CustomPostgres.port }}                           
{{- else }}
    DB_HOST="console-postgres.{{ .Release.Namespace }}.svc.cluster.local"
    DB_PORT=2285              
{{- end }}
    DB_PASSWORD="dbpassword-placeholder"
    DB_USER="operator"
    DB_SCHEMA="postgres"
    NEO4J_URI="bolt://viewer-neo4j.{{ .Release.Namespace }}.svc.cluster.local:7687"
    NEO4J_USER="neo4j"
    NEO4J_PASSWORD="imaging"
    DEBUG=False
    PORT=8082
    LOGS_FOLDER='/opt/imaging/open_ai-manager/logs'
    CSV_FOLDER='/opt/imaging/open_ai-manager/csvs'
    EXECUTABLE_PATH='/opt/imaging/open_ai-manager/nlp_modules/moduleBuilderLean'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: openaiappconfig
  namespace: {{.Release.Namespace}}
